#!/bin/bash

banner() {
    echo "
 _   _ _____ _____ ____    __  __                   _            
| \ | |_   _|  ___/ ___|  |  \/  | ___  _   _ _ __ | |_ ___ _ __ 
|  \| | | | | |_  \___ \  | |\/| |/ _ \| | | | '_ \| __/ _ \ '__|
| |\  | | | |  _|  ___) | | |  | | (_) | |_| | | | | ||  __/ |   
|_| \_| |_| |_|   |____/  |_|  |_|\___/ \__,_|_| |_|\__\___|_|
=================================================================
                                    By: Zavier Ferodova Al Fitroh
"
}

is_root() {
    if [[ $(id -u) == 0 ]]; then
        return 0 # true
    else
        return 1 # false
    fi
}

generate_unique_string() {
    # Define the characters to use
    characters="ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    length=5  # Change this to adjust the length of the string
    unique_string=""

    # Generate the unique string
    while [ ${#unique_string} -lt $length ]; do
        random_character="${characters:RANDOM % ${#characters}:1}"
        unique_string="${unique_string}${random_character}"
    done

    echo "$unique_string"
}

mount_disk() {
    printf "Enter disk identifier (ex: disk0s3): "
    read identifier
    ntfs-3g /dev/$identifier \
        /Volumes/NTFS-$(generate_unique_string) \
        -o volname="${VOLUME_NAME}" \
        -o local \
        -o negative_vncache \
        -o auto_xattr \
        -o auto_cache \
        -o noatime \
        -o windows_names \
        -o user_xattr \
        -o inherit \
        -o allow_other \
        "$@" &> /var/log/mount-ntfs-3g.log \
        && echo "Command completed!"
}

clear
external_disk=$(diskutil list | awk '/external/,/^$/')
if is_root; then
    if [ "$external_disk" = "" ]; then
        banner
        echo "External disks are empty!"
    else
        banner
        echo -e "$external_disk\n"
        mount_disk
    fi
else
    banner
    echo "Please run script using sudo!"
fi
